server:
  port: 8083

jwt:
  secret: secretkey123


spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password: 1234
    driverClassName: org.h2.Driver